### ISSUE TITLE
NullPointer on consent removal

### ISSUE THREAD

**Issue by AshStefanOltmann** [Countly/countly-sdk-java#17]
After updating to the latest release 20.11.2 I get an exception if I try to remove consent like this:

```
            Countly.onConsentRemoval(
                Config.Feature.Events,
                Config.Feature.Views,
                Config.Feature.Sessions
            )
```

This is the exception:

```
java.lang.NullPointerException
	at ly.count.sdk.java.internal.ModuleBackendMode.stop(ModuleBackendMode.java:71)
	at ly.count.sdk.java.internal.SDKModules.onConsentRemoval(SDKModules.java:171)
	at ly.count.sdk.java.Countly.onConsentRemoval(Countly.java:190)
```

It looks like that there is a missing check for NULL in https://github.com/Countly/countly-sdk-java/blob/ca61a7badb0a832c0dd1157517e5d93c09341283/sdk-java/src/main/java/ly/count/sdk/java/internal/ModuleBackendMode.java#L71

**Comment by ArtursKadikis** [comment]
Thank you for letting us know about this.

**Comment by StefanOltmann** [comment]
This is still an issue.

**Comment by StefanOltmann** [comment]
Fixed by pull request #22

**Comment by ArtursKadikis** [comment]
Sorry for not fixing this earlier, but as you noticed, we have fixed this in the PR.
We have also published this fix in the version "20.11.5".
